spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contacts
    username: user
    password: password
    hikari:
      schema: advanced_contacts_schema
  logging:
    level:
      root: debug
      spring.apps.contactsApp: debug